let rb_simple = {
    debug: false,
    name: "rb_simple",
    folder: "rb_simple",
    start_location: "pallet",
    font: "GameBoy_Font",
    font_size: "22px",

    // Config texts
    config_name: "Red/Blue Simple & Interiors",
    config_randomizer_author: "Archipelago",
    config_randomizer_link: "https://archipelago.gg/tutorial/Pokemon Red and Blue/setup/en",
    // config_tracker_author: "", 
    // config_tracker_link: "",

    // Tracker information
    locations: {
        // Cities
        pallet:           {x: 24,  y: 85,  w: 8,  h: 8,  name: "Pallet Town"                                                 },
        viridian:         {x: 24,  y: 64,  w: 8,  h: 8,  name: "Viridian City",                                              },
        pewter:           {x: 24,  y: 32,  w: 8,  h: 8,  name: "Pewter City"                                                 },
        cerulean:         {x: 104, y: 24,  w: 8,  h: 8,  name: "Cerulean City",                                              },
        vermilion:        {x: 104, y: 72,  w: 8,  h: 8,  name: "Vermilion City",                                             },
        lavender:         {x: 136, y: 48,  w: 8,  h: 8,  name: "Lavender Town"                                               },
        celadon:          {x: 80,  y: 48,  w: 8,  h: 8,  name: "Celadon City"                                                },
        saffron:          {x: 104, y: 48,  w: 8,  h: 8,  name: "Saffron City"                                                },
        fuchsia:          {x: 88,  y: 96,  w: 8,  h: 8,  name: "Fuchsia City"                                                },
        cinnabar:         {x: 24,  y: 112, w: 8,  h: 8,  name: "Cinnabar Island"                                             },
        indigo:           {x: 8,   y: 24,  w: 8,  h: 8,  name: "Indigo Plateau"                                              },

        // Routes                                                  },
        r10:              {x: 136, y: 32,  w: 8,  h: 8,  name: "Route 10\n& Power Plant"                                     },
        r12:              {x: 136, y: 72,  w: 8,  h: 8,  name: "Route 12 - 15"                                               },
        r22:              {x: 8,   y: 46,  w: 8,  h: 8,  name: "Route 22"                                                    },

        // Important locations
        cerulean_cave:    {x: 96,  y: 16,  w: 8,  h: 8,  name: "Cerulean Cave"                                               },
        department_store: {x: 80,  y: 40,  w: 8,  h: 8,  name: "Department Store\n& Elevator"                                            },
        // condominiums:     {x: 94,  y: 40,  w: 8,  h: 8,  name: "Celadon Condiminums"                                         },
        cinnabar_mansion: {x: 16,  y: 112, w: 8,  h: 8,  name: "Cinnabar Mansion"                                            },
        mt_moon:          {x: 64,  y: 24,  w: 8,  h: 8,  name: "Mt. Moon",             link_name: "Mt. Moon"        },
        rocket_hideout:   {x: 80,  y: 56,  w: 8,  h: 8,  name: "Rocket Hideout\n& Elevator"                                              },
        seafoam_islands:  {x: 56,  y: 112, w: 8,  h: 8,  name: "Seafoam Islands\nRoute 20",     link_name: "Seafoam Islands" },
        silph_1:          {x: 96,  y: 40,  w: 8,  h: 8,  name: "Silph Co.\n1F to 6F",           link_name: "Silph Co."       },
        silph_2:          {x: 112, y: 40,  w: 8,  h: 8,  name: "Silph Co.\n7F to 11F",          link_name: "Silph Co."       },
        // silph_elevator:   {x: 112, y: 56,  w: 8,  h: 8,  name: "Silph Co.\nElevator"                                         },
        safari_zone:      {x: 88,  y: 88,  w: 8,  h: 8,  name: "Safari Zone"                                                 },
        saffron_gym:      {x: 96,  y: 56,  w: 8,  h: 8,  name: "Saffron City\nGym",             link_name: "Saffron Gym"     },
        ss_anne:          {x: 104, y: 80,  w: 8,  h: 8,  name: "SS Anne"                                                     },
        victory_road:     {x: 8,   y: 32,  w: 8,  h: 8,  name: "Victory Road"                                                },
        gates:            {x: 64,  y: 8,   w: 8,  h: 8,  name: "Gates",                         link_name: "Gate"            },
        rocktunnel:       {x: 128, y: 32,  w: 8,  h: 8,  name: "Rock Tunnel",                                                   },
        pokemontower:     {x: 144, y: 48,  w: 8,  h: 8,  name: "Pokémon Tower"                                               },
        cycling_road:     {x: 48,  y: 72,  w: 8,  h: 8,  name: "Cycling Road"                                                },
        viridian_forest:  {x: 24,  y: 46,  w: 8,  h: 8,  name: "Viridian Forest"                                             },
        digletts_cave  :  {x: 112, y: 64,  w: 8,  h: 8,  name: "Digletts Cave"                                               },
    },

    // Undefined fields:
    // - link_type:     "warp"        / "mark"
    // - link:          warp_name     / mark_name
    // - link_location: location_name / <garbage>
    warps: {
    //    Removed because only Two-Ways
    //    condominiums: {
    //        entrance:                                                   {x: 79, y: 166, name: "Condominiums 1F" },
    //        stair1:                                                     {x: 39, y: 6, name: "Condominiums 1F" },
    //        door1:                                                      {x: 71, y: 25, name: "Condominiums 1F" },
    //        stair2:                                                     {x: 119, y: 6, name: "Condominiums 1F" },
    //        stair3:                                                     {x: 226, y: 6, name: "Condominiums 2F" },
    //        stair4:                                                     {x: 259, y: 44, name: "Condominiums 2F" },
    //        stair5:                                                     {x: 290, y: 7, name: "Condominiums 2F" },
    //        stair6:                                                     {x: 306, y: 41, name: "Condominiums 2F" },
    //        stair7:                                                     {x: 39, y: 237, name: "Condominiums 3F" },
    //        stair8:                                                     {x: 71, y: 277, name: "Condominiums 3F" },
    //        stair9:                                                     {x: 102, y: 239, name: "Condominiums 3F" },
    //        stair10:                                                    {x: 117, y: 276, name: "Condominiums 3F" },
    //        stair11:                                                    {x: 227, y: 238, name: "Condominiums 4F" },
    //        stair12:                                                    {x: 291, y: 238, name: "Condominiums 4F" },
    //        door2:                                                      {x: 228, y: 331, name: "Condominiums 4F" },
    //    },
        celadon: {
            martleft:                                          {x: 248, y: 193 },
            martright:                                         {x: 280, y: 161 },
            apart_front:                                       {x: 504, y: 129 },
            apart_back:                                        {x: 512, y: 33 },
            center:                                            {x: 776, y: 129 },
            corner_right:                                      {x: 648, y: 257 },
            corner_left:                                       {x: 568, y: 289 },
            house_left:                                        {x: 616, y: 417 },
            house_mid:                                         {x: 680, y: 385 },
            house_right:                                       {x: 808, y: 417 },
            gym:                                               {x: 312, y: 417 },
            underground:                                       {x: 968, y: 353 },
            saffron:                                           {x: 1048, y: 305 },
            snorlax:                                           {x: 40, y: 305 },
            cutexit:                                           {x: 40, y: 209 },
        },
        cerulean: {
            bike:                                              {x: 394, y: 439 },
            mart:                                              {x: 586, y: 439 },
            gym:                                               {x: 666, y: 343 },
            center:                                            {x: 490, y: 311 },
            house1:                                            {x: 394, y: 279 },
            house2front:                                       {x: 330, y: 215 },
            house2back:                                        {x: 362, y: 183 },
            house3front:                                       {x: 618, y: 215 },
            house3back:                                        {x: 650, y: 183 },
            bill:                                              {x: 537, y: 17,  name: "Bill's House" },
            daycare:                                           {x: 506, y: 679, name: "Route 5" },
            underground:                                       {x: 618, y: 775, name: "Route 5" },
            saffron:                                           {x: 499, y: 823, name: "Route 5" },
            mtmoon:                                            {x: 36,  y: 247, name: "Mt. Moon East" },
            cave:                                              {x: 250, y: 215, name: "Outside Cerulean Cave" },
        },
        cerulean_cave: {
            // ladder1:                                                   {x: 25, y: 101, name: "Cerulean Cave 1F" },
            // ladder2:                                                   {x: 24, y: 150, name: "Cerulean Cave 1F" },
            // ladder3:                                                   {x: 120, y: 70, name: "Cerulean Cave 1F" },
            // ladder4:                                                   {x: 441, y: 73, name: "Cerulean Cave 1F" },
            // ladder5:                                                   {x: 378, y: 116, name: "Cerulean Cave 1F" },
            // ladder6:                                                   {x: 297, y: 150, name: "Cerulean Cave 1F" },
            // ladder7:                                                   {x: 58, y: 183, name: "Cerulean Cave 1F" },
            entrance:                                                  {x: 401, y: 286, name: "Cerulean Cave 1F" },
            // ladder8:                                                   {x: 25, y: 405, name: "Cerulean Cave 2F" },
            // ladder9:                                                   {x: 154, y: 331, name: "Cerulean Cave 2F" },
            // ladder10:                                                  {x: 312, y: 467, name: "Cerulean Cave 2F" },
            // ladder11:                                                  {x: 362, y: 407, name: "Cerulean Cave 2F" },
            // ladder12:                                                  {x: 473, y: 329, name: "Cerulean Cave 2F" },
            // ladder13:                                                  {x: 57, y: 488, name: "Cerulean Cave 2F" },
            // ladder14:                                                  {x: 543, y: 250, name: "Cerulean Cave B1F" },
        },
        cinnabar: {
            mansion:                                                   {x: 67, y: 48 },
            lab:                                                       {x: 67, y: 144 },
            center:                                                    {x: 147, y: 179 },
            mart:                                                      {x: 211, y: 179 },
            gym:                                                       {x: 258, y: 51 },
            entrance:                                                  {x: 65, y: 364, name: "Cinnabar Lab" },
            // door1:                                                     {x: 154, y: 320, name: "Cinnabar Lab" },
            // door2:                                                     {x: 217, y: 356, name: "Cinnabar Lab" },
            // door3:                                                     {x: 283, y: 320, name: "Cinnabar Lab" },
        },
        cinnabar_mansion: {
            f1_entrance:                                       {x: 102, y: 440, name: "Cinnabar Mansion 1F" },
            f1_exit:                                           {x: 440, y: 440, name: "Cinnabar Mansion 1F" },
            // f1_stairs1:                                        {x: 96, y: 168,  name: "Cinnabar Mansion 1F" },
            // f1_stairs2:                                        {x: 352, y: 376, name: "Cinnabar Mansion 1F" },
            // f2_stairsleft:                                     {x: 584, y: 168, name: "Cinnabar Mansion 2F" },
            // f2_stairsright:                                    {x: 616, y: 198, name: "Cinnabar Mansion 2F" },
            // f2_stairstop:                                      {x: 600, y: 24,  name: "Cinnabar Mansion 2F" },
            // f2_stairsfareast:                                  {x: 904, y: 232, name: "Cinnabar Mansion 2F" },
            // f3_stairsnorth:                                    {x: 112, y: 495, name: "Cinnabar Mansion 3F" },
            // f3_stairsleft:                                     {x: 128, y: 639, name: "Cinnabar Mansion 3F" },
            // f3_stairsright:                                    {x: 416, y: 703, name: "Cinnabar Mansion 3F" },
            // b1f_stairs:                                        {x: 872, y: 831, name: "Cinnabar Mansion B1F" },
        },
        cycling_road: {
            flyhouse:                                          {x: 184, y: 65 },
            flyexit:                                           {x: 360, y: 65 },
            north:                                             {x: 360, y: 161 },
            south:                                             {x: 328, y: 561 },
        },
        department_store: {
            f1_left:                                           {x: 48,  y: 277, name: "Department Store 1F" },
            f1_right:                                          {x: 272, y: 277, name: "Department Store 1F" },
            // f1_stairs:                                         {x: 200, y: 213, name: "Department Store 1F" },
            // f1_elev:                                           {x: 24,  y: 213, name: "Department Store 1F" },
            // f2_left:                                           {x: 541, y: 228, name: "Department Store 2F" },
            // f2_right:                                          {x: 605, y: 198, name: "Department Store 2F" },
            // f2_elev:                                           {x: 365, y: 213, name: "Department Store 2F" },
            // f3__left:                                          {x: 882, y: 228, name: "Department Store 3F" },
            // f3__right:                                         {x: 946, y: 198, name: "Department Store 3F" },
            // f3__elev:                                          {x: 706, y: 213, name: "Department Store 3F" },
            // f4_left:                                           {x: 200, y: 377, name: "Department Store 4F" },
            // f4_right:                                          {x: 264, y: 347, name: "Department Store 4F" },
            // f4_elev:                                           {x: 24,  y: 362, name: "Department Store 4F" },
            // f5_left:                                           {x: 541, y: 377, name: "Department Store 5F" },
            // f5_right:                                          {x: 605, y: 347, name: "Department Store 5F" },
            // f5_elev:                                           {x: 365, y: 362, name: "Department Store 5F" },
            // elev1:                                             {x: 181, y: 112, name: "Department Elevator" },
            // elev2:                                             {x: 341, y: 112, name: "Department Elevator" },
            // elev3:                                             {x: 501, y: 112, name: "Department Elevator" },
            // elev4:                                             {x: 661, y: 112, name: "Department Elevator" },
            // elev5:                                             {x: 821, y: 112, name: "Department Elevator" },
        },
        fuchsia: {
            gym:                                               {x: 296, y: 417 },
            center:                                            {x: 520, y: 417 },
            warden:                                            {x: 648, y: 417 },
            fisherman:                                         {x: 712, y: 442 },
            fisherman2:                                        {x: 712, y: 385 },
            mart:                                              {x: 296, y: 193 },
            house1:                                            {x: 568, y: 193 },
            szone:                                             {x: 504, y: 33 },
            r15:                                               {x: 888, y: 257 },
            house2:                                            {x: 392, y: 417 },
            cycling:                                           {x: 40, y: 257 },
        },
        gates: {
            r11_1:                                                      {x: 43, y: 85, name: "Rt. 11 Gate" },
            r11_2:                                                      {x: 127, y: 86, name: "Rt. 11 Gate" },
            r11_3:                                                      {x: 111, y: 144, name: "Rt. 11 Gate" },
            r12_1:                                                      {x: 242, y: 42, name: "Rt. 12 Gate" },
            r12_2:                                                      {x: 242, y: 123, name: "Rt. 12 Gate" },
            r12_4:                                                      {x: 298, y: 107, name: "Rt. 12 Gate" },
            r15_1:                                                      {x: 383, y: 86, name: "Rt. 15 Gate" },
            r15_2:                                                      {x: 462, y: 84, name: "Rt. 15 Gate" },
            r15_3:                                                      {x: 448, y: 141, name: "Rt. 15 Gate" },
            r16_1:                                                      {x: 81, y: 334, name: "Rt. 16 Gate" },
            r16_2:                                                      {x: 161, y: 334, name: "Rt. 16 Gate" },
            r16_3:                                                      {x: 147, y: 388, name: "Rt. 16 Gate" },
            // r16_4:                                                      {x: 83, y: 235, name: "Rt. 16 Gate" },
            // r16_5:                                                      {x: 163, y: 237, name: "Rt. 16 Gate" },
            r18_1:                                                      {x: 311, y: 288, name: "Rt. 18 Gate" },
            r18_2:                                                      {x: 391, y: 291, name: "Rt. 18 Gate" },
            r18_3:                                                      {x: 375, y: 347, name: "Rt. 18 Gate" },
        },
        indigo: {
            indigo_inside:                                     {x: 160, y: 113, name: "Indigo Plateau - Inside" },
            indigo_outside:                                    {x: 160, y: 241, name: "Indigo Plateau - Outside" },
            victoryroad_exit:                                  {x: 88, y: 449,  name: "Indigo Plateau - Outside" },
        },
        lavender: {
            center:                                            {x: 381, y: 195 },
            fuji:                                              {x: 445, y: 259 },
            house_left:                                        {x: 381, y: 323 },
            house_right:                                       {x: 445, y: 353 },
            mart:                                              {x: 573, y: 323 },
            tower:                                             {x: 557, y: 195 },
            underground:                                       {x: 152, y: 163, name: "Route 8" },
            saffron:                                           {x: 56,  y: 275, name: "Route 8" },
            southexit:                                         {x: 501, y: 551 },
            rocktunnel:                                        {x: 435, y: 24,  name: "Route 10 South"},
        },
        mt_moon: {
            entrance:                                          {x: 240, y: 535, name: "Mt. Moon 1F" },
            // ladder1_1:                                         {x: 408, y: 215, name: "Mt. Moon 1F" },
            // ladder2_1:                                         {x: 280, y: 151, name: "Mt. Moon 1F" },
            // ladder3_1:                                         {x: 88, y: 55,   name: "Mt. Moon 1F" },
            // ladder1_2:                                         {x: 808, y: 775, name: "Mt. Moon B1F" },
            // ladder1_3:                                         {x: 1000, y: 583,name: "Mt. Moon B1F" },
            // ladder1_4:                                         {x: 248, y: 1015,name: "Mt. Moon B2F" },
            // ladder2_2:                                         {x: 1000, y: 487,name: "Mt. Moon B1F" },
            // ladder2_3:                                         {x: 872, y: 519, name: "Mt. Moon B1F" },
            // ladder2_4:                                         {x: 408, y: 727, name: "Mt. Moon B2F" },
            // ladder3_2:                                         {x: 948, y: 391, name: "Mt. Moon B1F" },
            ladder3_3:                                         {x: 1016, y: 423,name: "Mt. Moon B1F" },
            // ladder3_4:                                         {x: 344, y: 855, name: "Mt. Moon B2F" },
            // ladder4_1:                                         {x: 88, y: 695,  name: "Mt. Moon B2F" },
            // ladder4_2:                                         {x: 679, y: 423, name: "Mt. Moon B1F" },
            // ladder4_3:                                         {x: 935, y: 615, name: "Mt. Moon B1F" },
        },
        pallet: {
            house1:                                                      {x: 88, y: 73 },
            house2:                                                      {x: 216, y: 73 },
            lab:                                                         {x: 200, y: 171 },
        },
        pewter: {
            s_house:                                           {x: 72, y: 401 },
            center:                                            {x: 168, y: 337 },
            mart:                                              {x: 328, y: 209 },
            gym:                                               {x: 216, y: 209 },
            e_house:                                           {x: 424, y: 145 },
            w_museum:                                          {x: 184, y: 49 },
            e_museum:                                          {x: 264, y: 17 },
            southexit:                                         {x: 168, y: 689, name: "Route 2 North" },
            diglettscave:                                      {x: 313, y: 657, name: "Route 2 North" },
            centermoon:                                        {x: 700, y: 121, name: "Mt. Moon West" },
            mtmoon:                                            {x: 812, y: 121, name: "Mt. Moon West" },
            digletthouse:                                      {x: 483, y: 581, name: "Route 2 North" },
            southdiglett:                                      {x: 507, y: 697, name: "Route 2 North" },
        },
        pokemontower: {
            entrance:                                                    {x: 146, y: 263, name: "Pokemon Tower 1F" },
            // stair1:                                                      {x: 245, y: 136, name: "Pokemon Tower 1F" },
            // stair2:                                                      {x: 339, y: 164, name: "Pokemon Tower 2F" },
            // stair3:                                                      {x: 558, y: 127, name: "Pokemon Tower 2F" },
            // stair4:                                                      {x: 27, y: 428, name: "Pokemon Tower 3F" },
            // stair5:                                                      {x: 263, y: 474, name: "Pokemon Tower 3F" },
            // stair6:                                                      {x: 322, y: 431, name: "Pokemon Tower 4F" },
            // stair7:                                                      {x: 559, y: 432, name: "Pokemon Tower 4F" },
            // stair8:                                                      {x: 24, y: 736, name: "Pokemon Tower 5F" },
            // stair9:                                                      {x: 260, y: 739, name: "Pokemon Tower 5F" },
            // stair10:                                                     {x: 561, y: 729, name: "Pokemon Tower 6F" },
            // stair11:                                                     {x: 416, y: 842, name: "Pokemon Tower 6F" },
        },
        r10: {
            rocktunnel:                                        {x: 137, y: 33 , name: "Route 10 North" },
            center:                                            {x: 184, y: 65 , name: "Route 10 North" },
            powerplant:                                        {x: 104, y: 385, name: "Power Plant Outside" },
            north:                                             {x: 360, y: 120,  name: "Power Plant Inside"  },
            south:                                             {x: 432, y: 483, name: "Power Plant Inside"  },

        },
        r12: {
            north:                                             {x: 278, y: 49,  name: "Route 12 North"},
            east:                                              {x: 70,  y: 193, name: "Route 12 East" },
            house:                                             {x: 294, y: 417, name: "Route 12 House"},
            south:                                             {x: 198, y: 608, name: "Route 15"      },
        },
        rocktunnel: {
            // ladder1:                                           {x: 88, y: 33,   name: "Rock Tunnel 1F" },
            ladder2:                                           {x: 248, y: 33,  name: "Rock Tunnel 1F" },
            // ladder3:                                           {x: 280, y: 161, name: "Rock Tunnel 1F" },
            // ladder4:                                           {x: 600, y: 33,  name: "Rock Tunnel 1F" },
            // ladder5:                                           {x: 600, y: 257, name: "Rock Tunnel 1F" },
            ladder6:                                           {x: 248, y: 513, name: "Rock Tunnel 1F" },
            // ladder7:                                           {x: 56, y: 625,  name: "Rock Tunnel B1F" },
            // ladder8:                                           {x: 440, y: 625, name: "Rock Tunnel B1F" },
            // ladder9:                                           {x: 376, y: 753, name: "Rock Tunnel B1F" },
            // ladder10:                                          {x: 536, y: 977, name: "Rock Tunnel B1F" },
        },
        rocket_hideout: {
            cornersouth:                                       {x: 57, y: 859,  name: "Game Corner" },
            cornernorth:                                       {x: 89, y: 683,  name: "Game Corner" },
            b1fleft:                                           {x: 282, y: 108, name: "Rocket Hideout B1F" },
            // b1fright:                                          {x: 314, y: 108, name: "Rocket Hideout B1F" },
            // b1fstairs:                                         {x: 282, y: 460, name: "Rocket Hideout B1F" },
            // b1felevator:                                       {x: 338, y: 380, name: "Rocket Hideout B1F" },
            // b2fright:                                          {x: 874, y: 249, name: "Rocket Hideout B2F" },
            // b2fleft:                                           {x: 778, y: 204, name: "Rocket Hideout B2F" },
            // b2fstairs:                                         {x: 778, y: 428, name: "Rocket Hideout B2F" },
            // b2felev:                                           {x: 834, y: 380, name: "Rocket Hideout B2F" },
            // b3fstairs:                                         {x: 474, y: 588, name: "Rocket Hideout B3F" },
            // b3fstairs2:                                        {x: 378, y: 780, name: "Rocket Hideout B3F" },
            // b4fstairs:                                         {x: 746, y: 716, name: "Rocket Hideout B4F" },
            // b4felev:                                           {x: 834, y: 796, name: "Rocket Hideout B4F" },
            // elev1:                                             {x: 610, y: 73,  name: "Rocket Elevator" },
            // elev2:                                             {x: 738, y: 73,  name: "Rocket Elevator" },
            // elev3:                                             {x: 866, y: 73,  name: "Rocket Elevator" },
        },
        safari_zone: {
            c_entrance:                                        {x: 496, y: 1416,name: "Safari Zone Center" },
            // c_ne:                                              {x: 728, y: 1184,name: "Safari Zone Center" },
            // c_n:                                               {x: 496, y: 1016,name: "Safari Zone Center" },
            // c_nw:                                              {x: 264, y: 1184,name: "Safari Zone Center" },
            house1:                                            {x: 528, y: 1312,name: "Safari Zone Center" },
            // e_sw:                                              {x: 512, y: 912, name: "Safari Zone East" },
            // e_nw:                                              {x: 512, y: 664, name: "Safari Zone East" },
            house2:                                            {x: 904, y: 720, name: "Safari Zone East" },
            // n_s:                                               {x: 504, y: 552, name: "Safari Zone North" },
            // n_se:                                              {x: 808, y: 488, name: "Safari Zone North" },
            // n_sw1:                                             {x: 312, y: 552, name: "Safari Zone North" },
            // n_sw2:                                             {x: 216, y: 512, name: "Safari Zone North" },
            house3:                                            {x: 736, y: 32,  name: "Safari Zone North" },
            // w_ne1:                                             {x: 336, y: 584, name: "Safari Zone West" },
            // w_ne2:                                             {x: 432, y: 614, name: "Safari Zone West" },
            // w_se:                                              {x: 470, y: 952, name: "Safari Zone West" },
            surf:                                              {x: 56, y: 624,  name: "Safari Zone West" },
            house4:                                            {x: 184, y: 752, name: "Safari Zone West" },
        },
        saffron: {
            center:                                            {x: 228, y: 530 },
            psychic:                                           {x: 548, y: 530 },
            silphco:                                           {x: 372, y: 402 },
            house:                                             {x: 292, y: 242 },
            mart:                                              {x: 484, y: 242 },
            house2:                                            {x: 196, y: 146 },
            dojo:                                              {x: 500, y: 114 },
            gym:                                               {x: 628, y: 114 },
            northexit:                                         {x: 404, y: 18 },
            eastexit:                                          {x: 757, y: 354 },
            southexit:                                         {x: 404, y: 674 },
            westexit:                                          {x: 35, y: 355 },
        },
        saffron_gym: {
            entrance:                                                    {x: 145, y: 266, name: "Saffron Gym Entrance" },
            entrancewarp:                                                {x: 186, y: 232, name: "Saffron Gym Entrance" },
            blnw:                                                        {x: 26,  y: 233, name: "Saffron Gym SW" },
            blne:                                                        {x: 90,  y: 233, name: "Saffron Gym SW" },
            blsw:                                                        {x: 26,  y: 265, name: "Saffron Gym SW" },
            blse:                                                        {x: 90,  y: 266, name: "Saffron Gym SW" },
            lnw:                                                         {x: 26,  y: 137, name: "Saffron Gym W" },
            lne:                                                         {x: 90,  y: 136, name: "Saffron Gym W" },
            lsw:                                                         {x: 26,  y: 171, name: "Saffron Gym W" },
            lse:                                                         {x: 90,  y: 170, name: "Saffron Gym W" },
            tlnw:                                                        {x: 26,  y: 41,  name: "Saffron Gym NW" },
            tlne:                                                        {x: 90,  y: 40,  name: "Saffron Gym NW" },
            tlsw:                                                        {x: 26,  y: 73,  name: "Saffron Gym NW" },
            tlse:                                                        {x: 90,  y: 73,  name: "Saffron Gym NW" },
            tnw:                                                         {x: 153, y: 40,  name: "Saffron Gym N" },
            tne:                                                         {x: 185, y: 40,  name: "Saffron Gym N" },
            tsw:                                                         {x: 153, y: 73,  name: "Saffron Gym N" },
            tse:                                                         {x: 186, y: 73,  name: "Saffron Gym N" },
            trnw:                                                        {x: 251, y: 41,  name: "Saffron Gym NE" },
            trne:                                                        {x: 314, y: 40,  name: "Saffron Gym NE" },
            trsw:                                                        {x: 250, y: 73,  name: "Saffron Gym NE" },
            trse:                                                        {x: 314, y: 72,  name: "Saffron Gym NE" },
            rnw:                                                         {x: 249, y: 137, name: "Saffron Gym E" },
            rne:                                                         {x: 314, y: 137, name: "Saffron Gym E" },
            rsw:                                                         {x: 249, y: 169, name: "Saffron Gym E" },
            rse:                                                         {x: 313, y: 169, name: "Saffron Gym E" },
            brnw:                                                        {x: 249, y: 231, name: "Saffron Gym SE" },
            brne:                                                        {x: 314, y: 231, name: "Saffron Gym SE" },
            brsw:                                                        {x: 250, y: 264, name: "Saffron Gym SE" },
            brse:                                                        {x: 314, y: 264, name: "Saffron Gym SE" },
            center:                                                      {x: 185, y: 169, name: "Saffron Gym Center" },
        },
        seafoam_islands: {
            entrance:                                                    {x: 64,  y: 274, name: "Seafoam Islands 1F" },
            // ladder1:                                                     {x: 110, y: 39,  name: "Seafoam Islands 1F" },
            // ladder2:                                                     {x: 470, y: 57,  name: "Seafoam Islands 1F" },
            // ladder3:                                                     {x: 431, y: 241, name: "Seafoam Islands 1F" },
            exit:                                                        {x: 502, y: 279, name: "Seafoam Islands 1F" },
            // ladder4:                                                     {x: 640, y: 34,  name: "Seafoam Islands B1F" },
            // ladder5:                                                     {x: 659, y: 118, name: "Seafoam Islands B1F" },
            // ladder6:                                                     {x: 776, y: 106, name: "Seafoam Islands B1F" },
            // ladder7:                                                     {x: 860, y: 290, name: "Seafoam Islands B1F" },
            // ladder8:                                                     {x: 979, y: 268, name: "Seafoam Islands B1F" },
            // ladder9:                                                     {x: 1020,y: 181, name: "Seafoam Islands B1F" },
            // ladder10:                                                    {x: 1018,y: 85,  name: "Seafoam Islands B1F" },
            // ladder11:                                                    {x: 69,  y: 398, name: "Seafoam Islands B2F" },
            // ladder12:                                                    {x: 69,  y: 540, name: "Seafoam Islands B2F" },
            // ladder13:                                                    {x: 228, y: 423, name: "Seafoam Islands B2F" },
            // ladder14:                                                    {x: 468, y: 406, name: "Seafoam Islands B2F" },
            // ladder15:                                                    {x: 468, y: 504, name: "Seafoam Islands B2F" },
            // ladder16:                                                    {x: 471, y: 563, name: "Seafoam Islands B2F" },
            // ladder17:                                                    {x: 638, y: 508, name: "Seafoam Islands B3F" },
            // ladder18:                                                    {x: 687, y: 419, name: "Seafoam Islands B3F" },
            // ladder19:                                                    {x: 958, y: 372, name: "Seafoam Islands B3F" },
            // ladder20:                                                    {x: 958, y: 442, name: "Seafoam Islands B3F" },
            // ladder21:                                                    {x: 958, y: 542, name: "Seafoam Islands B3F" },
            // ladder22:                                                    {x: 118, y: 767, name: "Seafoam Islands B4F" },
            // ladder23:                                                    {x: 398, y: 705, name: "Seafoam Islands B4F" },
            // ladder24:                                                    {x: 348, y: 581, name: "Seafoam Islands B2F" },
            door1:                                                       {x: 678, y: 738, name: "Rt. 20 East" },
            door2:                                                       {x: 864, y: 756, name: "Rt. 20 West" },
        },
        silph_1: {
            entrance:                                                    {x: 245, y: 244, name: "Silph Co. 1F" },
            // elevator1:                                                   {x: 183, y: 184, name: "Silph Co. 1F" },
            // elevator2:                                                   {x: 301, y: 185, name: "Silph Co. 1F" },
            // stair1:                                                      {x: 907, y: 25,  name: "Silph Co. 2F" },
            // stair2:                                                      {x: 875, y: 49,  name: "Silph Co. 2F" },
            // elevator3:                                                   {x: 812, y: 23,  name: "Silph Co. 2F" },
            warp1:                                                       {x: 700, y: 36,  name: "Silph Co. 2F" },
            warp2:                                                       {x: 635, y: 224, name: "Silph Co. 2F" },
            warp3:                                                       {x: 923, y: 227, name: "Silph Co. 2F" },
            warp4:                                                       {x: 540, y: 75,  name: "Silph Co. 2F" },
            // stair3:                                                      {x: 421, y: 320, name: "Silph Co. 3F" },
            // stair4:                                                      {x: 388, y: 342, name: "Silph Co. 3F" },
            // elevator4:                                                   {x: 328, y: 319, name: "Silph Co. 3F" },
            warp5:                                                       {x: 438, y: 368, name: "Silph Co. 3F" },
            warp6:                                                       {x: 55,  y: 372, name: "Silph Co. 3F" },
            warp7:                                                       {x: 53,  y: 453, name: "Silph Co. 3F" },
            warp8:                                                       {x: 180, y: 454, name: "Silph Co. 3F" },
            warp9:                                                       {x: 376, y: 456, name: "Silph Co. 3F" },
            warp10:                                                      {x: 56,  y: 518, name: "Silph Co. 3F" },
            warp11:                                                      {x: 439, y: 518, name: "Silph Co. 3F" },
            // stair5:                                                      {x: 908, y: 320, name: "Silph Co. 4F" },
            // stair6:                                                      {x: 875, y: 337, name: "Silph Co. 4F" },
            // elevator5:                                                   {x: 812, y: 320, name: "Silph Co. 4F" },
            warp12:                                                      {x: 763, y: 368, name: "Silph Co. 4F" },
            warp13:                                                      {x: 669, y: 390, name: "Silph Co. 4F" },
            warp14:                                                      {x: 765, y: 453, name: "Silph Co. 4F" },
            warp15:                                                      {x: 541, y: 518, name: "Silph Co. 4F" },
            // stair7:                                                      {x: 420, y: 614, name: "Silph Co. 5F" },
            // stair8:                                                      {x: 390, y: 633, name: "Silph Co. 5F" },
            // elevator6:                                                   {x: 325, y: 615, name: "Silph Co. 5F" },
            warp16:                                                      {x: 438, y: 659, name: "Silph Co. 5F" },
            warp17:                                                      {x: 181, y: 649, name: "Silph Co. 5F" },
            warp18:                                                      {x: 55,  y: 812, name: "Silph Co. 5F" },
            // elevator7:                                                   {x: 812, y: 611, name: "Silph Co. 6F" },
            // stair10:                                                     {x: 778, y: 630, name: "Silph Co. 6F" },
            // stair11:                                                     {x: 725, y: 611, name: "Silph Co. 6F" },
            warp19:                                                      {x: 572, y: 662, name: "Silph Co. 6F" },
            warp20:                                                      {x: 893, y: 659, name: "Silph Co. 6F" },
            warp21:                                                      {x: 151, y: 809, name: "Silph Co. 5F" },
        },
        silph_2: {
            // stair1:                                                      {x: 359, y: 26,  name: "Silph Co. 7F" },
            // elevator1:                                                   {x: 293, y: 40,  name: "Silph Co. 7F" },
            // stair2:                                                      {x: 261, y: 25,  name: "Silph Co. 7F" },
            warp1:                                                       {x: 346, y: 226, name: "Silph Co. 7F" },
            warp2:                                                       {x: 89,  y: 30,  name: "Silph Co. 7F" },
            warp3:                                                       {x: 88,  y: 96,  name: "Silph Co. 7F" },
            // stair4:                                                      {x: 650, y: 29,  name: "Silph Co. 8F" },
            // stair5:                                                      {x: 698, y: 50,  name: "Silph Co. 8F" },
            // elevator2:                                                   {x: 731, y: 29,  name: "Silph Co. 8F" },
            warp4:                                                       {x: 618, y: 63,  name: "Silph Co. 8F" },
            warp5:                                                       {x: 618, y: 129, name: "Silph Co. 8F" },
            warp6:                                                       {x: 491, y: 157, name: "Silph Co. 8F" },
            warp7:                                                       {x: 491, y: 220, name: "Silph Co. 8F" },
            // stair6:                                                      {x: 213, y: 327, name: "Silph Co. 9F" },
            // stair7:                                                      {x: 259, y: 343, name: "Silph Co. 9F" },
            // elevator3:                                                   {x: 293, y: 327, name: "Silph Co. 9F" },
            warp8:                                                       {x: 150, y: 377, name: "Silph Co. 9F" },
            warp9:                                                       {x: 280, y: 520, name: "Silph Co. 9F" },
            // stair8:                                                      {x: 642, y: 325, name: "Silph Co. 10F" },
            // stair9:                                                      {x: 689, y: 344, name: "Silph Co. 10F" },
            // stair10:                                                     {x: 721, y: 325, name: "Silph Co. 10F" },
            warp10:                                                      {x: 737, y: 395, name: "Silph Co. 10F" },
            warp11:                                                      {x: 674, y: 461, name: "Silph Co. 10F" },
            warp12:                                                      {x: 739, y: 522, name: "Silph Co. 10F" },
            // stair10:                                                     {x: 474, y: 630, name: "Silph Co. 11F" },
            // elevator4:                                                   {x: 537, y: 609, name: "Silph Co. 11F" },
            warp13:                                                      {x: 376, y: 656, name: "Silph Co. 11F" },
            // elevator5:                                                   {x: 722, y: 323, name: "Silph Co. 10F" },
        },
        // silph_elevator: {
            // f1:                                                          {x: 37, y: 54, name: "Silph Elevator 1F" },
            // f2:                                                          {x: 129, y: 53, name: "Silph Elevator 2F" },
            // f3:                                                          {x: 221, y: 53, name: "Silph Elevator 3F" },
            // f4:                                                          {x: 38, y: 145, name: "Silph Elevator 4F" },
            // f5:                                                          {x: 127, y: 147, name: "Silph Elevator 5F" },
            // f6:                                                          {x: 221, y: 145, name: "Silph Elevator 6F" },
            // f7:                                                          {x: 39, y: 241, name: "Silph Elevator 7F" },
            // f8:                                                          {x: 127, y: 244, name: "Silph Elevator 8F" },
            // f9:                                                          {x: 222, y: 243, name: "Silph Elevator 9F" },
            // f10:                                                         {x: 88, y: 336, name: "Silph Elevator 10F" },
            // f11:                                                         {x: 180, y: 336, name: "Silph Elevator 11F" },
        // },
        ss_anne: {
            entrance:                                                    {x: 522, y: 20, name: "S.S. Anne 1F" },
            // stair1:                                                      {x: 34,  y: 159, name: "S.S. Anne 1F" },
            // door1:                                                       {x: 132, y: 145, name: "S.S. Anne 1F" },
            // door2:                                                       {x: 212, y: 203, name: "S.S. Anne 1F" },
            // door3:                                                       {x: 293, y: 146, name: "S.S. Anne 1F" },
            // door4:                                                       {x: 374, y: 203, name: "S.S. Anne 1F" },
            // door5:                                                       {x: 454, y: 144, name: "S.S. Anne 1F" },
            // door6:                                                       {x: 613, y: 144, name: "S.S. Anne 1F" },
            // stair2:                                                      {x: 733, y: 274, name: "S.S. Anne 1F" },
            // stair3:                                                      {x: 647, y: 419, name: "S.S. Anne 2F" },
            // door7:                                                       {x: 535, y: 484, name: "S.S. Anne 2F" },
            // door8:                                                       {x: 472, y: 531, name: "S.S. Anne 2F" },
            // door9:                                                       {x: 409, y: 484, name: "S.S. Anne 2F" },
            // door10:                                                      {x: 344, y: 531, name: "S.S. Anne 2F" },
            // door11:                                                      {x: 280, y: 484, name: "S.S. Anne 2F" },
            // door12:                                                      {x: 216, y: 531, name: "S.S. Anne 2F" },
            // stair4:                                                      {x: 103, y: 497, name: "S.S. Anne 2F" },
            // stair5:                                                      {x: 103, y: 420, name: "S.S. Anne 2F" },
            // stair6:                                                      {x: 539, y: 652, name: "S.S. Anne 3F" },
            // door13:                                                      {x: 217, y: 650, name: "S.S. Anne 3F" },
            // stair7:                                                      {x: 584, y: 726, name: "S.S. Anne B1F" },
            // door14:                                                      {x: 521, y: 743, name: "S.S. Anne B1F" },
            // door15:                                                      {x: 456, y: 693, name: "S.S. Anne B1F" },
            // door16:                                                      {x: 391, y: 743, name: "S.S. Anne B1F" },
            // door17:                                                      {x: 328, y: 693, name: "S.S. Anne B1F" },
            // door18:                                                      {x: 264, y: 743, name: "S.S. Anne B1F" },
            // door19:                                                      {x: 54,  y: 321, name: "S.S. Anne 1F" },
        },
        vermilion: {
            fisherman:                                         {x: 120, y: 409 },
            center:                                            {x: 184, y: 454 },
            fanclub:                                           {x: 152, y: 569 },
            house1:                                            {x: 248, y: 569 },
            mart:                                              {x: 376, y: 569 },
            house2:                                            {x: 376, y: 665 },
            gym:                                               {x: 200, y: 665 },
            ssanne:                                            {x: 305, y: 902 },
            saffron:                                           {x: 520, y: 41,  name: "Route 6" },
            underground:                                       {x: 632, y: 137, name: "Route 6" },
            diglett:                                           {x: 712, y: 569, name: "Route 11" },
            rightexit:                                         {x: 856, y: 601, name: "Route 11" },

        },
        victory_road: {
            entrance2:                                                   {x: 169, y: 435, name: "Victory Road 1F" },
            // ladder1:                                                     {x: 20,  y: 172, name: "Victory Road 1F" },
            // ladder2:                                                     {x: 368, y: 295, name: "Victory Road 2F" },
            // ladder3:                                                     {x: 389, y: 153, name: "Victory Road 2F" },
            // ladder4:                                                     {x: 869, y: 414, name: "Victory Road 2F" },
            // ladder5:                                                     {x: 827, y: 320, name: "Victory Road 2F" },
            // ladder6:                                                     {x: 907, y: 269, name: "Victory Road 2F" },
            exit:                                                        {x: 934, y: 318, name: "Victory Road 2F" },
            // ladder7:                                                     {x: 107, y: 543, name: "Victory Road 3F" },
            // ladder8:                                                     {x: 503, y: 641, name: "Victory Road 3F" },
            // ladder9:                                                     {x: 559, y: 662, name: "Victory Road 3F" },
            // ladder10:                                                    {x: 584, y: 800, name: "Victory Road 3F" },
        },
        viridian: {
            center:                                            {x: 636, y: 573 },
            mart:                                              {x: 732, y: 477 },
            s_house:                                           {x: 604, y: 413 },
            n_house:                                           {x: 604, y: 317 },
            gym:                                               {x: 780, y: 285 },
            r22:                                               {x: 136, y: 381, name: "Route 22"},
            r2left:                                            {x: 476, y: 67,  name: "Route 2 South" },
            r2right:                                           {x: 668, y: 3,   name: "Route 2 South" },
        },
        viridian_forest: {
            north:                                             {x: 23,  y: 33  },
            south:                                             {x: 271, y: 721 },
        },
        digletts_cave: {
            north:                                             {x: 93, y: 69 },
            south:                                             {x: 605, y: 485 },
            // northladder:                                       {x: 346, y: 66 },
            // southladder:                                       {x: 606, y: 294 },
            // northexit:                                         {x: 314, y: 114 },
            // southexit:                                         {x: 574, y: 342 },
        },
        r22: {
            r22_north:                                         {x: 168, y: 36,  name: "Route 22 - North" },
            r22_south:                                         {x: 128, y: 276, name: "Route 22 - South" },
        },
    },

    // Numbers are meant to be to check if exist any marks/progress in the maps
    // if null, then we don't do tracking
    // if undefined, then we don't draw the mark
    marks: [
        [["unknown",     0], ["corridor",    0], ["dead_end",  null], ["event",        0], ["center",        0], ["mart",       0], ["one_way",     null]],
        [["normal",      0], ["fighting",     0], ["flying",       0], ["poison",        0], ["ground",     0], ["rock",           0], ["bug",         0], ["ghost",        0]],
        [["fire",         0], ["water",        0], ["grass",         0], ["electric",   0], ["psychic",        0], ["ice",         0], ["dragon",       0]],
        [["1",           0], ["2",            0], ["3",            0], ["4",             0], ["5",          0], ["6",              0], ["7",           0], ["8",            0]],
        [["boulder_badge", 0], ["cascade_badge", 0], ["thunder_badge", 0], ["rainbow_badge", 0], ["soul_badge", 0], ["marsh_badge",  0], ["volcano_badge", 0], ["earth_badge",  0]],
        [["frlg_bush",   0], ["frlg_surf",    0], ["frlg_boulder", 0], ["frlg_darkness", 0], ["bike_needed", 0], ["bike_voucher",  0], ["parcel",        0], ["poke_flute", 0],],
        [["card_key",    0], ["secret_key",      0], ["lift_key",    0], ["plant_key",     0], ["mansion_key",0], ["hideout_key", 0], ["safaripass", 0], ["tea",          0]],
        [["gold_teeth",  0], ["silph_scope",   0], ["ss_ticket",    0], ["itemfinder",    0], ["coincase",    0], ["townmap",    0], ["helix",    0], ["pokedoll", 0]],
        [["frlg_rival", 0], ["fuji", 0],["trade", 0],["pokedex", 0]],

    ],
    progress: [
    ],

    modifiers: [
        [["#ce4069", 0], ["#4d90d5", 0], ["#ff9c54", 0], ["#74cec0", 0], ["#f3d23b", 0], ["#90c12c", 0], ["#743683", 0], ["#ec8fe6", 0], ["#654321", 0], ["#5a5366", 0], ["#014f01", 0], ["#00146b", 0]]
    ],
};